Database:
  Driver: "postgres"
  Host: "localhost"
  Port: 5432
  Username: "postgres"
  Password: "123456"
  DbName: "oz"
  SslMode: "disable"
  LogLevel: 2 #Silent = 1, Error, Warn, Info

Cache:
  Addr: "localhost:6379"
  Db: 2

Port: 8080
Environment: "production"

JwtSecret: "w56Wr8KOa1q42CabTvtxXtl6z0RrqSoP"
JwtExpireMinute: 1440 #one day

TimeZone: "Europe/Istanbul"